### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by crhuber** [umutbozkurt/django-rest-framework-mongoengine#106]
Last update 6 months ago. Many issues say "this will be fixed this weekend" (6 months ago). 
I appreciate the hard work gone into this project. But if it will no longer be maintained please let us know 
Thanks

**Comment by Jcbobo88** [comment]
the drf is changed quite a lot...at least a maintainer is needed

**Comment by Jcbobo88** [comment]
I'm using a lot this library and if you need I could help as maintainer.

**Comment by malderete** [comment]
Is there any news on this? Why the project seem dead? I'd like to get a reply :) thanks!

**Comment by crhuber** [comment]
I got this email from Umut
"I really wanted to keep maintaining it, but the community is not helping at all. And I was extremely busy working, so I dropped maintaining it.
But, if you are willing to help we can give it a final try. If you are interested of course

Let me know until this weekend so we can jump right in"

**Comment by Jcbobo88** [comment]
I receave the same mail, 
I'm interested in have this library updated but I'm not really skilled in maintenance and I think I can not handle it alone.

**Comment by qwiglydee** [comment]
@Jcbobo88, are you gathering stuff in your own fork or going to maintain this repo?
(i'm not sure how such stuff works)

**Comment by Jcbobo88** [comment]
@qwiglydee I want to maintain this repo

**Comment by vpaslav** [comment]
THANK YOU :).

**Comment by qwiglydee** [comment]
Ok. It will survive.

I've setup [milestone 3.x](https://github.com/umutbozkurt/django-rest-framework-mongoengine/milestones) with primary goal to gain compatibility with mainstream DRF and testfulness (or whataver it is called).
Most issues created is actually work in progress, just mixed up in my working copy.

However, backward compatibility will be broken in favour of DRF-compatibility (due to refactoring DocumentField, and changing to DRF's native Dict|List).
