### ISSUE TITLE
<class 'mongoengine.fields.EmbeddedDocumentListField'> is not supported, yet

### ISSUE THREAD

**Issue by JohnnyJai** [umutbozkurt/django-rest-framework-mongoengine#108]
Hi,

I am using "django-rest-framework-mongoengine==2.0.2" with "mongoengine==0.9.0".
I need to use EmbeddedDocumentList and according to the traceback I got.

```
 File "/Users/XXX/Development/server/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/Users/XXX/Development/server/env/lib/python2.7/site-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/Users/XXX/Development/server/env/lib/python2.7/site-packages/rest_framework/response.py", line 59, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "/Users/XXX/Development/server/env/lib/python2.7/site-packages/rest_framework/renderers.py", line 736, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/XXX/Development/server/env/lib/python2.7/site-packages/rest_framework/renderers.py", line 686, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "/Users/XXX/Development/server/env/lib/python2.7/site-packages/rest_framework/renderers.py", line 636, in get_raw_data_form
    content = renderer.render(serializer.data, accepted, context)
  File "/Users/XXX/Development/server/env/lib/python2.7/site-packages/rest_framework/serializers.py", line 463, in data
    ret = super(Serializer, self).data
  File "/Users/XXX/Development/server/env/lib/python2.7/site-packages/rest_framework/serializers.py", line 216, in data
    self._data = self.get_initial()
  File "/Users/XXX/Development/server/env/lib/python2.7/site-packages/rest_framework/serializers.py", line 343, in get_initial
    for field in self.fields.values()
  File "/Users/XXX/Development/server/env/lib/python2.7/site-packages/rest_framework/serializers.py", line 312, in fields
    for key, value in self.get_fields().items():
  File "/Users/XXX/Development/server/env/lib/python2.7/site-packages/rest_framework_mongoengine/serializers.py", line 255, in get_fields
    type(model_field))
```

This is my model definition:

```
class TestHistory(EmbeddedDocument):
    """
    Test History model
    """
    name = StringField()
    created = DateTimeField(default=datetime.datetime.now)

class Test(Document):
    """
    Test model
    """
    history = EmbeddedDocumentListField(TestHistory)
    created = DateTimeField(default=datetime.datetime.now)
```

KeyError I got is that: class 'mongoengine.fields.EmbeddedDocumentListField'> is not supported, yet.
Will it be supported soon? Thanks for helping.

Best Regards,
Johnny

**Comment by Jcbobo88** [comment]
if you look the example you will see  ListField(EmbeddedDocumentField(BlogExtension)) 
if you have time you could implement the EmbeddedDocumentListField yourself

if you are starting a new project from scratch take in care that this  repository is not updated for a long time

**Comment by Jcbobo88** [comment]
I have found a workaround.... you can override the serialization of your field

in the serializer add history= historySerializer(many=True)

**Comment by JohnnyJai** [comment]
Hi Jcbobo88,

Thanks for all the help, will talk to the others in the team and take a little reflection if we should use this library.

**Comment by Jcbobo88** [comment]
I'm using it... But i'm thinking to rebuild it from scratch for the latest
drf version...my problem is that require too mutch work only for myself,
but with some collaborator this will be possible in a short period.

If you want use the embeddedDocumentField you could also use explicit
nexted serializer.
OuterSerializer(documentSerializer):
  EmbeddedDocument=embeddedDocumentSerializer()

You can override create and update method of the serializer for enable
nexted write (default drf behaviour)
Il 07/lug/2015 20:51, "Johnny Ha" <notifications@github.com> ha scritto:

**Comment by Jcbobo88** [comment]
Sorry for the double reply but i want to add some detail.

I have a fork where i do update and some fix in order to use the library
inside mine project (started some time ago not now)

If you are starting from scrath think about move to other framework (not
django) in order to use mongoengine because they have moved django support
to a separated repository and are loocking for mantainer (last
django-momgoengine update was about 1 year ago).

i don't know django so well to do it..

If you need to use mongodb take in to consideration also turbogears is less
documented but works well with mongodb

I think a lot of people has moved to rails or minestack (node express
mongo)
If you need some help on drf-mongoenine fell free to asks

Good evening
Andrea
 Il 07/lug/2015 20:59, "andrea boetto" <boettoandrea@gmail.com> ha scritto:

**Comment by JohnnyJai** [comment]
Hi Jcbobo88,

I don't understand it: today we are using ListField(EmbeddedDocumentField(TestHistory)) because of it is not possible to use EmbeddedDocumentListField(TestHistory).

Can you explain more about what you mean with history= historySerializer(many=True)?

**Comment by JohnnyJai** [comment]
I am new to django and python, one of my teammate is using django and python on one of his project. That is why we use django and python, I am mostly a java and javascript developer.

**Comment by Jcbobo88** [comment]
Of course,
Have you read django rest framework documentation?
The embeddedDocument serialization is some kind of nexted serialization (
you can find the doc here
http://www.django-rest-framework.org/api-guide/serializers/#dealing-with-nested-objects
)

So you could do the same in order to make serialization possible
Then or set the nexted field to read_only and create an other endpoint for
managing nexted resources (for nexed routers theere is an other library)

Or override the create and update serializer method

Sorry for my english and my error but i'm coming back to home now and i'm
from the phone)
Il 07/lug/2015 21:12, "Johnny Ha" <notifications@github.com> ha scritto:

**Comment by Jcbobo88** [comment]
Django works very well with relazional dbs the mongodb integration is not
the best...

If you are a good js programmer you could think about nodejs but is
mandatory to take in care that a lot of library are not free to use but
requore a fee proportional to the number of used coders
 Il 07/lug/2015 21:15, "Johnny Ha" <notifications@github.com> ha scritto:

**Comment by qwiglydee** [comment]
@JohnnyJai, why do you need EmbeddedDocumentListField in the first place?
In ME-0.9.0 it seems like it's just a wrapper for ListField(EmbeddedDocumentField()).
Does it have some neat functionality other, then wrapped constructor?

**Comment by qwiglydee** [comment]
This should work in current trunk.
Please, check it.
